# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            chrisjrob
tagline:          'GNU Linux, Perl and FLOSS'
description:      'GNU Linux, Perl and FLOSS'
url:              http://chrisjrob.github.io
baseurl:          /

author:
  name:           'Christopher Roberts'
  url:            https://twitter.com/chrisjrob

paginate:         10

excerpt_separator: <!--more-->

# Custom vars
social:
  plus:           112653355770650909703
  twitter:        chrisjrob
  github:         chrisjrob
  facebook:       chrisjrob

disqus:
  shortname:      'chrisjrob'
