# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            chrisjrob
tagline:          'GNU Linux, Perl and FLOSS'
description:      ''
url:              http://chrisjrob.github.io
baseurl:          /

author:
  name:           'Christopher Roberts'
  url:            https://twitter.com/chrisjrob

paginate:         10

excerpt_separator: <!--more-->

# Custom vars
social:
  plus:           https://plus.google.com/u/0/112653355770650909703/
  twitter:        https://twitter.com/chrisjrob/
  github:         https://github.com/chrisjrob/

disqus:
  shortname:      'chrisjrob'
