# Plugins
plugins: [jekyll-paginate]

# Dependencies
# markdown:         redcarpet
markdown:         kramdown

# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter:      pygments
highlighter:      rouge

# Permalinks
# permalink:        pretty
permalink:        /:year/:month/:day/:title/

# Setup
title:            chrisjrob
tagline:          'GNU Linux, Perl and FLOSS'
description:      'GNU Linux, Perl and FLOSS'
url:              https://chrisjrob.com
baseurl:          ''

author:
  name:           'Chris Roberts'
  email:          'chrisjrob@gmail.com'
  url:            https://twitter.com/chrisjrob

paginate:         10

excerpt_separator: <!--more-->

# Custom vars
sitemap:          'sitemap.txt'
social:
  mastodon:       https://mastodon.social/@chrisjrob
  twitter:        chrisjrob
  github:         chrisjrob
  facebook:       chrisjrob

disqus:
  shortname:      'chrisjrob'

show_drafts:      false
future:           false
