# Site settings
title: chrisjrob
email: chrisjrob@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Warning - may contain nuts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrisjrob.github.io" # the base hostname & protocol for your site
twitter_username: chrisjrob
github_username:  chrisjrob

# Build settings
markdown: kramdown
